version: '3.8'

services:
  devsecops-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devsecops-app
    ports:
      - "5001:5000"
    networks:
      - devsecops-net

  devsecops-app-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devsecops-app-test
    command: pytest tests/test_app.py
    depends_on:
      - devsecops-app
    networks:
      - devsecops-net

  jenkins:
    build:
      context: .
      dockerfile: Jenkins.Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devsecops-net

networks:
  devsecops-net:
    driver: bridge


