version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-main
    user: root
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_home_fresh:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devsecops-net

  devsecops-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devsecops-app-main
    restart: unless-stopped
    volumes:
      - ./app:/app
    networks:
      - devsecops-net

networks:
  devsecops-net:
    driver: bridge
