version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Jenkins.Dockerfile
    image: jenkins-devsecops
    container_name: jenkins-main
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:8080/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: devsecops-app
    container_name: devsecops-app-main
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      jenkins:
        condition: service_healthy

networks:
  default:
    name: devsecops-net
    driver: bridge

volumes:
  jenkins_home:
    name: jenkins_home
